version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
    - "25960:80"
    volumes:
    - .:/var/www/public
    depends_on:
    - db
  db:
    image: mysql:5.7
    ports:
    - "25963:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=kovacsolt
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=kovacsolt_next
    volumes:
    - "mysql_data:/var/lib/mysql"
volumes:
  mysql_data: { driver: local }